# Generated by Django 6.0.6 on 2026-07-11 22:54

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='assigne_a',
            new_name='assignee',
        ),
        migrations.AddField(
            model_name='projet',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='membres',
            field=models.ManyToManyField(related_name='projets_membres', to=settings.AUTH_USER_MODEL),
        ),
    ]
