# Generated by Django 6.0.6 on 2026-08-08 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_assigne_a_tache_assignee_projet_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='deadline',
            new_name='date_echeance',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='assignee',
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='projets_membres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
