# Generated by Django 6.0.6 on 2026-08-12 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_nom_projet_titre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
    ]
